---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ .Values.targetApp.name }}
    role: patch-operator
  name: {{ .Values.targetApp.name }}-patch-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.targetApp.name }}-patch-operator
subjects:
- kind: ServiceAccount
  name: {{ .Values.targetApp.name }}-patch-operator
  namespace: {{ .Values.targetApp.namespace }}